language: java
jdk:
    - openjdk10
    - openjdk11
    - openjdk9
sudo: false
install: true
before_script: |
    if [ `java -version 2>&1 | grep -c " 9\."` -ne 0 ]; then export MAVEN_OPTS="--add-modules=java.xml.bind"; fi
script: mvn integration-test
